MU WPCOM: Port the starter-page-templates feature from ETK (#38475)
* Initial commit

* Fix build compilation errors due to dependencies

* changelog

* Update dependency

* Remove typing to avoid adding peer dependency

* Update dependency

* Fix for SassError: Can't find stylesheet to import

* Update page-pattern-modal package

* Revert import path change

* Fix missing __i18n_text_domain__ in page-pattern-modal package

* Refactoring and cleaning up feature code

* Show starter-page-templates feature instead of core modal

* Fix lint

* Fix lint

* Revert cleaning code

* Fix namespace

* Fix lint

* Fix lint

* Fix lint

* Add back sideload images

* Add comment

* Fix lint and disable some Phan checks

* Fix version

* Fix lint

* Move initialization and checks

* Move class initialization

* Fix versions

* Fix tests

* Fix the modal is not shown

---------

Co-authored-by: arthur <arthur.chu@automattic.com>

Committed via a GitHub action: https://github.com/Automattic/jetpack/actions/runs/10173358274

Upstream-Ref: Automattic/jetpack@6c500254a5df1a197bca0a5a72083cd9728b4c03