Boost: Save concatenated JS/CSS in files on server (#41056)
* Update URLs for concatenated assets

* Add WIP code to handle new URL

* add changelog

* Fix URLs for concatenated assets pointing to outside wp-content files

* Store concatenated output in files

* Update file name to indicate that file is minified

* Refactor serving and storing of concatenated files

* Refactor file name building

* Pass request uri instead of reaching in global array

* Rely on existing code for allowed extensions instead of hard-coded list

* Move handling static concatenation to a separate file

* Enhance cache cleanup functionality.

* Files are now purged based on last access time, one week.
* A separate cleanup for static cache directories.
* Files older than a week are removed regardless of access time.

* Don't deviate too much from how optimize used to garbage collect.

Instead of a week, go with twice the access time, which is 2 days.
Longer than that, and we will need to rebuild the cached files in
a cron job, and then we won't know how many cached minified files
were really obsolete and shouldn't be updated any more

* Load the minification engine that builds the minified file

* Load the minification loader

* Always load minification classes, for maintenance tasks

* Allow new static cache file to go for a week

The old files exist for only a day because they're not checked.
I'll add a cron job that tries to maintain the new files.

* loader.php has to be loaded from the template_redirect action

* Add a maintenance function that deletes obsolete minified files

This function compares the minified file with the dependencies. If they
are newer, then the minified file is deleted, so it can be regenerated
by the 404 handler.

* /Users/donncha/dev/jetpack/vendor/sirbrillig/phpcs-Fixes for PHAN errors.

projects/plugins/boost/app/lib/minify/functions-service-new.php:7
Error: Plugin PhanPluginNeverReturnFunction Function \jetpack_boost_handle_minify_request() never returns and has a return type of void, but phpdoc type never could be used instead
projects/plugins/boost/app/lib/minify/functions-service-new.php:156
Error: Plugin PhanPluginUseReturnValueInternalKnown Expected to use the return value of the internal function/method \preg_replace_callback
projects/plugins/boost/app/lib/minify/functions-service-new.php:213
Error: UndefError PhanPossiblyUndeclaredVariable Variable $mime_type is possibly undeclared
projects/plugins/boost/app/lib/minify/functions-service-new.php:243
Error: TypeError PhanTypePossiblyInvalidDimOffset Possibly invalid offset 'extension' of $file_info of array type array{dirname:string,basename:string,extension?:string,filename:string}
projects/plugins/boost/app/lib/minify/functions-service-new.php:254
Error: TypeError PhanTypePossiblyInvalidDimOffset Possibly invalid offset 'extension' of $file_info of array type array{dirname:string,basename:string,extension?:string,filename:string}

* Always load minification include files to avoid problems uninstalling

jetpack_boost_cache_maintenance() in functions-service-new.php is used
by the helper script when uninstalling, but won't be loaded when
uninstalling if it's loaded on template_redirect.

* This file is loaded by app/lib/minify/loader.php now

* If file_age is 0 then delete files.

* No need to maintain obsolete static files. Just delete them.
* Make sure to delete static files in boost-cache when file_age is 0
* No need to check filemtime or fileatime. Just delete.

* Add comment to explain jetpack_boost_cache_maintenance()

* Just in case WP is installed in a directory. Not always at "/"

* Fix the maintenance script so it gets the cached list of files

* Only check moved cache folder for legacy folder

* Add is_404() tester to minification

* Are we testing the is_404() handler?

* Test the is_404() check when activating minification modules

* Serve legacy minified files if new static files not supported

* Fix the @charset bug in the old minified files too

* Run the 404 tester at least once in wp-admin/

* Updated PHAN baseline

* Updated PHAN baseline

* Use str_contains instead of strpos

Trying to force the e2e tests to run again

* Store static minification bool in a site option

On a multisite install, this will stop the plugin checking if is_404
works every time a new user logs in to /wp-admin/.

* Add code to cleanup cached files of deactivated module

It will delete the corresponding static files, css or js.

* The static cache dir doesn't change, it's a string always

We don't as yet allow the static cache dir to be changed so it's safe to
remove the $use_cache checks. get_static_cache_dir_path() always returns
a path to the directory.

* Return early if $cache_dir is not defined.

No need to go through other checks. It will log a proper error for this
too.

* Remove todo

There's already an issue for that.

* Improve readability of concat Config class

* Rename helper method

* Rename function

* Fix incorrect return type

* Rename files so they make more sense

* Add proper check for file parts

* Remove types

* Update comments

* Fix variable name

* Update minify css/js to use activate/deactivate to run their setup

* Fix fatal errors due to file renames

* Fix incorrect json_decode usage

* Fix static analysis complaining about possibly undefined variables

* Fix incorrect comparison

* Remove redundant check

* Make phan happy

* Update static analysis baseline

* Improve path checking and add clarification

* Make the glob pattern more precise

* Fix the directory security check so static files can be created

* Use str_contains() to look for the string

It's checking for the existence of the string, not position.

* Avoid checking again if the file is deleted.

If the first check succeeded, the file will be deleted. No need to check
the filemtime() on a deleted file and cause a warning.

* Add a comment to describe what happens here.

* Remove unnecessary activate trait from minification classes

* Add function to schedule 404 tester cronjob

---------

Co-authored-by: Donncha O Caoimh <5656673+donnchawp@users.noreply.github.com>
Co-authored-by: Liam Sarsfield <liamsarsfield1499@gmail.com>

Committed via a GitHub action: https://github.com/Automattic/jetpack/actions/runs/13162604890

Upstream-Ref: Automattic/jetpack@113e0b82cc0141b1f0de2ca6d481a849fb05bcc6