Fix/mapkit map.additems validation error (#45476)
* Fix: MapKit map.addItems validation error

Starting with MapKit JS versions 5.80.*, Map Blocks with markers create
errors that crash JS with the following error in the console:

Error: [MapKit] Map.addItems expected an Annotation, Overlay, ItemCollection, or Array of valid items at index 0, but got `[object Object]` instead.

This problem is due to a change in how 5.80.* validates passed
parameters to the addItems and showItems functions. The validation does
a "instanceof Array" check, which fails to properly recognize Array
values created in a realm different from the realm the MapKit library is
executing in.

The fix uses the currentWindow object to remake the annotations array
in the same realm as the realm that the MapKit library runs in.

* changelog

Committed via a GitHub action: https://github.com/Automattic/jetpack/actions/runs/18468094676

Upstream-Ref: Automattic/jetpack@01f4127b4b36a41e4cb435750cfc7c0e4a5d1e28